ViniAlvesMartins/tech-challenge-fiap

- src/adapter/inbound/controller/order_controller.go
- src/adapter/inbound/handler/http_server/app.go
> implemnts order by id

- src/adapter/outbound/repository/order_repository.go
> Ajuste query criacao order

- kustomize/kustomization.yaml
- kustomize/namespace.yaml
- kustomize/postgress.yaml
- kustomize/zeburguer.yaml
https://github.com/users/ViniAlvesMartins/projects/4?pane=issue&itemId=45355495
To create the app resources localy use the command inside the root folder:
`kubectl apply -k ./kustomize/`
> Add kubernetes resources

- .github/workflows/ci-docker.yaml
- infra/prod/Dockerfile
Add workflow to build docker image from Repository.
> Add workflow to build zeburguer image

- src/application/contract/repository.go
- src/application/contract/use_case.go
- src/application/use_case/client.go
- src/controller/controller/order_controller.go
- src/external/handler/http_server/app.go
- src/external/repository/client_repository.go
> fix: implementacao de validacao de criacao de pedidos

- kustomize/ze-burguer.yaml
> Fix k8s resources

- kustomize/ze-burguer.yaml
Rollback to use official image on ze-burguer deployment
> Rollback official image

- doc/swagger/docs.go
- doc/swagger/swagger.json
- doc/swagger/swagger.yaml
- src/controller/controller/order_controller.go
- src/controller/serializer/input/status_order.go
> correcao atualizacao status

- .github/workflows/ci-cd.yaml
Add migration job on CD workflow!
> Add migration job

- cmd/main.go
> Removing load of envs from file

- README.md
- doc/swagger/docs.go
- doc/swagger/swagger.json
- doc/swagger/swagger.yaml
> Updating swagger doc and readme

- kustomize/ze-burguer.yaml
> Change RDS secret

- doc/apis/Ze_burguer.postman_collection.json
> ajuste collection

- sonar-project.properties
> Add sonar exceptions

- .github/workflows/ci-cd.yaml
> Remove aws credentials step

- kustomize/ze-burguer.yaml
> Update envs values

- src/external/handler/sqs/consumer.go
> feat: trocando account id da aws

- kustomize/ze-burguer.yaml
> feat: alteração do RDS

- src/controller/controller/client_controller.go
> feat: alteração no swagger

- infra/docker/prod/Dockerfile
> feat: ajuste FROM golang to 1:22

- .github/workflows/ci-cd.yaml
> ajuste kustomize

- infra/kustomize/ze-burguer.yaml
> Change database

- internal/application/use_case/order.go
> Fixing order sent

- README.md
> feat: inclusao relatorio ripd

- README.md
> fix: ajustando diretorio

- README.md
> fix: ajuste doc
